apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app: {{ include "rabbitmq.name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "rabbitmq.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rabbitmq.name" . }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt && rabbitmq-server"
          ports:
            - containerPort: {{ .Values.rabbitmq.service.amqpPort }}
              name: amqp
            - containerPort: {{ .Values.rabbitmq.service.managementPort }}
              name: management
            - containerPort: {{ .Values.rabbitmq.service.mqttPort }}
              name: mqtt
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.global.env.RABBITMQ_DEFAULT_USER }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.global.env.RABBITMQ_DEFAULT_PASS }}"
            - name: no_proxy
              value: "{{ .Values.global.proxy.no_proxy }},localhost,127.0.0.1,audioanalyzer,pipelinemanager,videoingestion,minio-server,postgresql,video-summary-nginx,rabbitmq,multimodal-embedding-ms,vdms-dataprep,vdms-vectordb,videosearch,.svc.cluster.local"
            - name: http_proxy
              value: "{{ .Values.global.proxy.http_proxy }}"
            - name: https_proxy
              value: "{{ .Values.global.proxy.https_proxy }}"
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
