rabbitmq:
  enabled: true
ovms:
  enabled: true
videoingestion:
  enabled: true
audioanalyzer:
  enabled: true

pipelinemanager:
  env:
    SUMMARY_FEATURE: "FEATURE_ON"
    SEARCH_FEATURE: "FEATURE_OFF"

videosummaryui:
  name: videosummaryui
  feature:
    summary: "FEATURE_ON"
    search: "FEATURE_OFF"
    mux: "ATOMIC"
