apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.modeldownload.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
    {{- if .Values.modeldownload.affinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.modeldownload.affinity.key }}
                operator: In
                values:
                - {{ .Values.modeldownload.affinity.value }}
        {{- end }}
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
      containers:
        - name: model-download
          image: "{{ .Values.modeldownload.image.registry }}model-download:{{ .Values.modeldownload.image.tag }}"
          imagePullPolicy: {{ .Values.modeldownload.image.pullPolicy }}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: {{ .Values.modeldownload.readinessProbe.httpGet.path }}
              port: {{ .Values.modeldownload.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.modeldownload.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.modeldownload.readinessProbe.periodSeconds }}
          env:
            - name: HTTP_PROXY
              value: "{{ .Values.global.proxy.http_proxy }}"
            - name: HTTPS_PROXY
              value: "{{ .Values.global.proxy.https_proxy }}"
            - name: NO_PROXY
              value: "{{ .Values.global.proxy.no_proxy }}"
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "1"
            - name: HF_TOKEN
              value: "{{ .Values.modeldownload.env.HUGGINGFACEHUB_API_TOKEN }}"
            - name: MODEL_PATH
              value: "/opt/models"
            - name: ENABLED_PLUGINS
              value: "{{ .Values.modeldownload.env.ENABLED_PLUGINS }}"
            - name: OVMS_RELEASE_TAG
              value: "{{ .Values.modeldownload.env.OVMS_RELEASE_TAG }}"
            - name: GETI_WORKSPACE_ID
              value: "{{ .Values.modeldownload.env.GETI_WORKSPACE_ID }}"
            - name: GETI_HOST
              value: "{{ .Values.modeldownload.env.GETI_HOST }}"
            - name: GETI_TOKEN
              value: "{{ .Values.modeldownload.env.GETI_TOKEN }}"
            - name: GETI_SERVER_API_VERSION
              value: "{{ .Values.modeldownload.env.GETI_SERVER_API_VERSION }}"
            - name: GETI_SERVER_SSL_VERIFY
              value: "{{ .Values.modeldownload.env.GETI_SERVER_SSL_VERIFY }}"
            - name: HLS_3D_POSE_CHECKPOINT_URL
              value: "{{ .Values.modeldownload.env.HLS_3D_POSE_CHECKPOINT_URL }}"
            - name: HLS_ECG_BASE_URL
              value: "{{ .Values.modeldownload.env.HLS_ECG_BASE_URL }}"
            - name: HLS_RPPG_MODEL_URL
              value: "{{ .Values.modeldownload.env.HLS_RPPG_MODEL_URL }}"
          command: ["/opt/entrypoint.sh"]
          args: ["--plugins", "{{ .Values.modeldownload.env.ENABLED_PLUGINS | default "all" }}"]
          volumeMounts:
            - name: models
              mountPath: /opt/models
            {{- if .Values.modeldownload.gpu.enabled }}
            - name: dri-device
              mountPath: /dev/dri
            {{- end }}
          {{- if .Values.modeldownload.gpu.enabled }}
          resources:
            requests:
              {{ .Values.modeldownload.gpu.key }}: 1
            limits:
              {{ .Values.modeldownload.gpu.key }}: 1
          securityContext:
            privileged: true
            runAsUser: 1001
            runAsGroup: 1001
          {{- end }}
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: models-pvc
        {{- if .Values.modeldownload.gpu.enabled }}
        - name: dri-device
          hostPath:
            path: /dev/dri
            type: Directory
{{- end }}