# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  model_download_service:
    image: ${REGISTRY}model-download:${TAG}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: model-download
    command: --plugins ${ENABLED_PLUGINS:-all}
    environment:
      - no_proxy=${no_proxy:-}
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - HF_TOKEN=${HUGGINGFACEHUB_API_TOKEN:-}
      - ENABLED_PLUGINS=${ENABLED_PLUGINS}
      - MODEL_PATH=${MODEL_PATH}
      - OVMS_RELEASE_TAG=${OVMS_RELEASE_TAG:-v2025.4.1}
      - GETI_HOST=${GETI_HOST}
      - GETI_TOKEN=${GETI_TOKEN}
      - GETI_WORKSPACE_ID=${GETI_WORKSPACE_ID}
      - GETI_SERVER_API_VERSION=${GETI_SERVER_API_VERSION:-v1}
      - GETI_SERVER_SSL_VERIFY=${GETI_SERVER_SSL_VERIFY:-False}
      - HLS_3D_POSE_CHECKPOINT_URL=${HLS_3D_POSE_CHECKPOINT_URL}
      - HLS_ECG_BASE_URL=${HLS_ECG_BASE_URL}
      - HLS_RPPG_MODEL_URL=${HLS_RPPG_MODEL_URL}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 180s
    ports:
      - "8200:8000"
    volumes:
      - ${MODEL_PATH:-~/models}:/opt/models
    group_add:
      - ${USER_GROUP_ID:-1001}