
name: "[DLSPS] Package helm charts weekly "
run-name: "[DLSPS] Package helm charts weekly"
on:
  workflow_dispatch:
    inputs:
      helm-chart-tag:
        description: 'Helm chart tag'
        required: true
        type: string

permissions: {}
jobs:
  publish-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps:
    - name: Check out edge-ai-libraries repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: edge-ai-libraries-repo
        persist-credentials: false
    - name: Install Helm
      uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 #v4.3.1
      with:
        version: v3.15.2
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Package Helm Chart
      env:
        HELM_CHART_TAG: ${{ inputs.helm-chart-tag }}
      run: |
        cd edge-ai-libraries-repo/microservices/dlstreamer-pipeline-server/helm
        helm package . --version "${HELM_CHART_TAG}" --app-version "${HELM_CHART_TAG}"
    - name: Push to GHCR
      env:
        HELM_CHART_TAG: ${{ inputs.helm-chart-tag }}
        GITHUB_REPO: ${{ github.repository }}
      run: |
        CHART_PACKAGE=$(ls edge-ai-libraries-repo/microservices/dlstreamer-pipeline-server/helm/dlstreamer-pipeline-server-"${HELM_CHART_TAG}".tgz)
        helm push $CHART_PACKAGE oci://ghcr.io/${GITHUB_REPO}/

    - name: Update Github Summary
      env:
        HELM_CHART_TAG: ${{ inputs.helm-chart-tag }}
        GITHUB_REPO: ${{ github.repository }}
      run: |
        echo "### ✅ DLStreamerPipelineServer helm chart published to github container registry" >> $GITHUB_STEP_SUMMARY
          echo "- Registry: \`oci://ghcr.io/${GITHUB_REPO}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Version: \`${HELM_CHART_TAG}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Pull command: \`helm pull oci://ghcr.io/${GITHUB_REPO}/dlstreamer-pipeline-server --version ${HELM_CHART_TAG}\`" >> $GITHUB_STEP_SUMMARY
    - name: Clean up
      if: always()
      run: |
        rm -rf edge-ai-libraries-repo